export const POKER_GAME_ADDRESS = (
  import.meta.env.VITE_POKER_GAME_ADDRESS ??
  '0xC2D1b8cea516eEcB711fd1F01B6DaCC6195a8408'
) as `0x${string}`

export const POKER_GAME_ABI = [
  { type: 'event', name: 'TableCreated', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'creator', type: 'address', indexed: true }, { name: 'smallBlind', type: 'uint256' }, { name: 'bigBlind', type: 'uint256' }, { name: 'maxPlayers', type: 'uint8' }] },
  { type: 'event', name: 'PlayerJoined', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'player', type: 'address', indexed: true }, { name: 'seat', type: 'uint8' }, { name: 'buyIn', type: 'uint256' }] },
  { type: 'event', name: 'PlayerLeft', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'player', type: 'address', indexed: true }, { name: 'cashOut', type: 'uint256' }] },
  { type: 'event', name: 'StatusChanged', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'from', type: 'uint8' }, { name: 'to', type: 'uint8' }] },
  { type: 'event', name: 'PlayerActed', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'player', type: 'address', indexed: true }, { name: 'action', type: 'uint8' }, { name: 'value', type: 'uint256' }] },
  { type: 'event', name: 'CommunityRevealed', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'stage', type: 'uint8' }, { name: 'cards', type: 'uint8[5]' }] },
  { type: 'event', name: 'ShowdownResult', inputs: [{ name: 'tableId', type: 'uint256', indexed: true }, { name: 'winner', type: 'address', indexed: true }, { name: 'winningRank', type: 'uint32' }, { name: 'payout', type: 'uint256' }] },
  { type: 'event', name: 'Deposited', inputs: [{ name: 'player', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'newBalance', type: 'uint256' }] },
  { type: 'event', name: 'Withdrawn', inputs: [{ name: 'player', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }, { name: 'newBalance', type: 'uint256' }] },
  { type: 'event', name: 'SessionAuthorized', inputs: [{ name: 'player', type: 'address', indexed: true }, { name: 'session', type: 'address', indexed: true }, { name: 'expiresAt', type: 'uint64' }] },
  { type: 'event', name: 'SessionRevoked', inputs: [{ name: 'player', type: 'address', indexed: true }, { name: 'session', type: 'address', indexed: true }] },

  {
    type: 'function', name: 'sessions', stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'tableId', type: 'uint256' },
      { name: 'handId', type: 'uint256' },
      { name: 'maxPlayers', type: 'uint8' },
      { name: 'minBuyIn', type: 'uint256' },
      { name: 'maxBuyIn', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'dealerIndex', type: 'uint8' },
      { name: 'activePlayerIndex', type: 'uint8' },
      { name: 'playerCount', type: 'uint8' },
      { name: 'pot', type: 'uint256' },
      { name: 'currentBet', type: 'uint256' },
      { name: 'smallBlind', type: 'uint256' },
      { name: 'bigBlind', type: 'uint256' },
      { name: 'vrfPending', type: 'bool' },
      { name: 'vrfRequestBlock', type: 'uint256' },
      { name: 'deckSeed', type: 'bytes32' },
      { name: 'deckCommitment', type: 'bytes32' },
      { name: 'deckCursor', type: 'uint8' },
      { name: 'communityCount', type: 'uint8' },
      { name: 'saltsCommitted', type: 'uint8' },
      { name: 'saltsRevealed', type: 'uint8' },
      { name: 'lastActionBlock', type: 'uint256' },
      { name: 'actionTimeout', type: 'uint256' },
    ],
  },
  {
    type: 'function', name: 'getSession', stateMutability: 'view',
    inputs: [{ name: 'tableId', type: 'uint256' }],
    outputs: [
      { name: 'handId', type: 'uint256' }, { name: 'status', type: 'uint8' },
      { name: 'playerCount', type: 'uint8' }, { name: 'dealerIndex', type: 'uint8' },
      { name: 'pot', type: 'uint256' }, { name: 'currentBet', type: 'uint256' },
      { name: 'deckCommitment', type: 'bytes32' }, { name: 'communityCount', type: 'uint8' },
      { name: 'vrfPending', type: 'bool' }, { name: 'saltsCommitted', type: 'uint8' },
      { name: 'saltsRevealed', type: 'uint8' },
    ],
  },
  { type: 'function', name: 'getPlayers', stateMutability: 'view', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [{ name: '', type: 'address[]' }] },
  {
    type: 'function', name: 'getPlayerState', stateMutability: 'view',
    inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }],
    outputs: [
      { name: 'stake', type: 'uint256' }, { name: 'currentBet', type: 'uint256' },
      { name: 'lastAction', type: 'uint8' }, { name: 'isActive', type: 'bool' },
      { name: 'seatIndex', type: 'uint8' }, { name: 'holeCommitment', type: 'bytes32' },
      { name: 'hasRevealed', type: 'bool' }, { name: 'handRank', type: 'uint32' },
    ],
  },
  {
    type: 'function', name: 'getRevealedCards', stateMutability: 'view',
    inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }],
    outputs: [
      { name: 'c0s', type: 'uint8' }, { name: 'c0v', type: 'uint8' },
      { name: 'c1s', type: 'uint8' }, { name: 'c1v', type: 'uint8' },
    ],
  },
  { type: 'function', name: 'getCommunityCards', stateMutability: 'view', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [{ name: '', type: 'uint8[5]' }] },
  { type: 'function', name: 'tableCount', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256' }] },
  { type: 'function', name: 'getBalance', stateMutability: 'view', inputs: [{ name: 'player', type: 'address' }], outputs: [{ name: '', type: 'uint256' }] },
  { type: 'function', name: 'isSessionAuthorized', stateMutability: 'view', inputs: [{ name: 'player', type: 'address' }, { name: 'session', type: 'address' }], outputs: [{ name: '', type: 'bool' }] },

  { type: 'function', name: 'deposit', stateMutability: 'payable', inputs: [], outputs: [] },
  { type: 'function', name: 'withdraw', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'authorizeSession', stateMutability: 'nonpayable', inputs: [{ name: 'session', type: 'address' }, { name: 'expiresAt', type: 'uint64' }], outputs: [] },
  { type: 'function', name: 'revokeSession', stateMutability: 'nonpayable', inputs: [{ name: 'session', type: 'address' }], outputs: [] },
  { type: 'function', name: 'joinTable', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'buyIn', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'joinTableFor', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }, { name: 'buyIn', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'leaveTable', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'leaveTableFor', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }], outputs: [] },
  { type: 'function', name: 'commitSalt', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'saltHash', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'commitSaltFor', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }, { name: 'saltHash', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'requestDeal', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'requestDealFor', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }], outputs: [] },
  { type: 'function', name: 'playerAction', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'action', type: 'uint8' }, { name: 'value', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'playerActionFor', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }, { name: 'action', type: 'uint8' }, { name: 'value', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'forceTimeout', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'forceShowdownTimeout', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'revealHoleCards', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'salt', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'revealHoleCardsFor', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }, { name: 'player', type: 'address' }, { name: 'salt', type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'evaluateShowdown', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'settleLastStanding', stateMutability: 'nonpayable', inputs: [{ name: 'tableId', type: 'uint256' }], outputs: [] },

  // Custom errors — required for viem to decode revert reasons instead of
  // showing generic "Missing or invalid parameters".
  { type: 'error', name: 'Unauthorized', inputs: [] },
  { type: 'error', name: 'OnlyVRFProvider', inputs: [{ name: 'expected', type: 'address' }, { name: 'actual', type: 'address' }] },
  { type: 'error', name: 'TableNotFound', inputs: [{ name: 'tableId', type: 'uint256' }] },
  { type: 'error', name: 'TableFull', inputs: [] },
  { type: 'error', name: 'NotSeated', inputs: [{ name: 'player', type: 'address' }] },
  { type: 'error', name: 'AlreadySeated', inputs: [{ name: 'player', type: 'address' }] },
  { type: 'error', name: 'InvalidBuyIn', inputs: [{ name: 'sent', type: 'uint256' }, { name: 'min', type: 'uint256' }, { name: 'max', type: 'uint256' }] },
  { type: 'error', name: 'NotYourTurn', inputs: [{ name: 'expected', type: 'address' }, { name: 'actual', type: 'address' }] },
  { type: 'error', name: 'NotEnoughPlayers', inputs: [] },
  { type: 'error', name: 'InvalidAction', inputs: [] },
  { type: 'error', name: 'HandAlreadyInProgress', inputs: [] },
  { type: 'error', name: 'VRFRequestPending', inputs: [{ name: 'tableId', type: 'uint256' }] },
  { type: 'error', name: 'NoVRFRequestPending', inputs: [{ name: 'tableId', type: 'uint256' }] },
  { type: 'error', name: 'TimeoutNotReached', inputs: [{ name: 'current', type: 'uint256' }, { name: 'deadline', type: 'uint256' }] },
  { type: 'error', name: 'SaltAlreadyCommitted', inputs: [{ name: 'player', type: 'address' }] },
  { type: 'error', name: 'NotAllSaltsCommitted', inputs: [{ name: 'committed', type: 'uint8' }, { name: 'required', type: 'uint8' }] },
  { type: 'error', name: 'AlreadyRevealed', inputs: [{ name: 'player', type: 'address' }] },
  { type: 'error', name: 'SaltMismatch', inputs: [{ name: 'player', type: 'address' }] },
  { type: 'error', name: 'CommitmentMismatch', inputs: [{ name: 'player', type: 'address' }, { name: 'expected', type: 'bytes32' }, { name: 'computed', type: 'bytes32' }] },
  { type: 'error', name: 'NotAllPlayersRevealed', inputs: [] },
  { type: 'error', name: 'PlayerNotActive', inputs: [{ name: 'player', type: 'address' }] },
] as const
